[package]
name = "protobuf-gen"
version = "0.1.0"
authors = ["Reio Piller <reio@heathmont.net>"]
edition = "2018"

[dependencies]
prost-types = "0.6.1"
prost = "0.6.1"
# alloc_counter = "0.0.4"
tempfile = "3"

[dev-dependencies]
